[package]
name = "day_9"
version = "0.1.0"
edition = "2024"

[dependencies]
mt_logger = { git = "https://github.com/fabian-plaehn/mt_logger.git", branch = "my-branch" }
utils = { path = "../utils" }
indicatif = "0.17"